#!/bin/bash
set -euxo pipefail

curl -fsSL https://pixi.sh/install.sh | bash
export PATH="$HOME/.pixi/bin:$PATH"

pixi install --locked
pixi shell-hook -e default -s bash

echo 'eval "$(pixi shell-hook)"' >> $HOME/.bashrc
